### ISSUE TITLE
output file name id

### ISSUE THREAD

**Issue by 97-109-107** [evmcl/erudite#2]
Is it possible to prefix the name of the final file with an incremental id of some sort (the Instapaper's internal id would be enough)?

Context - I'm looking for a way to sort the outputted articles by date added.

btw. Thanks for being so fast with the last issue!

**Comment by evmcl** [comment]
Hi again.

Sorry, there isn't a way to do this with Erudite currently. It's not a feature I can myself adding in the near future.

Best regards,

E.
